# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Antony Polukhin 2016-2017.

#
# See https://svn.boost.org/trac/boost/wiki/TravisCoverals for description of this file
# and how it can be used with Boost libraries.
#
# File revision #5 + modifications

init:
    - set BRANCH_TO_TEST=master  # Change to Boost branch you wish to test with. Use %APPVEYOR_REPO_BRANCH% for current branch.

###############################################################################################################
# From this point and below code is same for all the Boost libs
###############################################################################################################

version: 1.65.{build}-{branch}
 
# branches to build
branches:
  except:
    - gh-pages

environment:
  matrix:
    - TOOLSET_PATH: C:\Qt\5.8\mingw53_32\bin;C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
      BOOST_FLAGS: toolset=gcc --layout=system variant=release
      BUILD_COMMAND: mingw32-make -j2

    - TOOLSET_PATH: C:\Qt\5.8\msvc2015_64\bin
      BOOST_FLAGS: toolset=msvc address-model=64
      BUILD_COMMAND: nmake /NOLOGO

skip_tags: true

before_build:
    - set PATH=%PATH%;%TOOLSET_PATH%
    - echo "Testing %APPVEYOR_PROJECT_NAME%"

    # Cloning Boost libraries (fast nondeep cloning)
    - set BOOST=C:/boost-local
    - git init %BOOST%
    - cd %BOOST%
    - git remote add --no-tags -t %BRANCH_TO_TEST% origin https://github.com/boostorg/boost.git
    - git fetch --depth=1
    - git checkout %BRANCH_TO_TEST%
    - git submodule update --init --merge --jobs 16
    - git remote set-branches --add origin %BRANCH_TO_TEST%
    #- git pull --recurse-submodules        # Updaes submodules to most recent version. Not required


build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
    # Packages from nuget.
    - nuget install libpng -ExcludeVersion -NonInteractive
    # Building Boost.
    - bootstrap.bat
    - b2.exe headers
    - b2.exe -j4 %BOOST_FLAGS% architecture=x86 link=static --with-program_options --with-filesystem --with-system --with-test --with-atomic --with-thread --with-timer --with-date_time --with-chrono --with-regex --with-random --with-context stage
    - cd %APPVEYOR_BUILD_FOLDER%

after_build:
before_test:
test_script:
    # Building examples.
    - qmake "BOOST_PATH=%BOOST%" "CONFIG+=debug" BoostBook.pro
    - "%BUILD_COMMAND%"
    - python ./test.py -v

after_test:
on_success:
on_failure:
on_finish:
